-- Datos de prueba realistas: al menos 25 registros por tabla
INSERT INTO app_usuario(usuario, password, rol, nombre) VALUES ('admin', 'secret', 'admin', 'Administrador general');
INSERT INTO app_usuario(usuario, password, rol, nombre) VALUES ('inventario', 'secret', 'inventario', 'Encargado de inventario');
INSERT INTO app_usuario(usuario, password, rol, nombre) VALUES ('ventas', 'secret', 'ventas', 'Cajero de ventas');
INSERT INTO app_usuario(usuario, password, rol, nombre) VALUES ('reportes', 'secret', 'reportes', 'Analista de reportes');
INSERT INTO app_usuario(usuario, password, rol, nombre) VALUES ('auditor', 'secret', 'auditor', 'Auditor de tienda');

INSERT INTO categoria(nombre, descripcion) VALUES ('Bebidas', 'Productos líquidos para consumo diario');
INSERT INTO categoria(nombre, descripcion) VALUES ('Snacks', 'Botanas y alimentos ligeros');
INSERT INTO categoria(nombre, descripcion) VALUES ('Lácteos', 'Leche, yogures y derivados');
INSERT INTO categoria(nombre, descripcion) VALUES ('Panadería', 'Pan y repostería');
INSERT INTO categoria(nombre, descripcion) VALUES ('Limpieza', 'Productos de limpieza del hogar');
INSERT INTO categoria(nombre, descripcion) VALUES ('Higiene', 'Artículos de cuidado personal');
INSERT INTO categoria(nombre, descripcion) VALUES ('Abarrotes', 'Productos básicos de despensa');
INSERT INTO categoria(nombre, descripcion) VALUES ('Carnes', 'Productos cárnicos empacados');
INSERT INTO categoria(nombre, descripcion) VALUES ('Congelados', 'Productos refrigerados y congelados');
INSERT INTO categoria(nombre, descripcion) VALUES ('Frutas', 'Frutas frescas');
INSERT INTO categoria(nombre, descripcion) VALUES ('Verduras', 'Verduras frescas');
INSERT INTO categoria(nombre, descripcion) VALUES ('Mascotas', 'Alimentos y accesorios para mascotas');
INSERT INTO categoria(nombre, descripcion) VALUES ('Papelería', 'Útiles escolares y oficina');
INSERT INTO categoria(nombre, descripcion) VALUES ('Electrónica', 'Accesorios electrónicos');
INSERT INTO categoria(nombre, descripcion) VALUES ('Farmacia', 'Productos básicos de farmacia');
INSERT INTO categoria(nombre, descripcion) VALUES ('Cocina', 'Utensilios de cocina');
INSERT INTO categoria(nombre, descripcion) VALUES ('Ropa', 'Textiles básicos');
INSERT INTO categoria(nombre, descripcion) VALUES ('Ferretería', 'Herramientas pequeñas');
INSERT INTO categoria(nombre, descripcion) VALUES ('Jardinería', 'Productos para jardín');
INSERT INTO categoria(nombre, descripcion) VALUES ('Dulces', 'Confitería');
INSERT INTO categoria(nombre, descripcion) VALUES ('Café y té', 'Bebidas calientes');
INSERT INTO categoria(nombre, descripcion) VALUES ('Cereales', 'Cereales y granolas');
INSERT INTO categoria(nombre, descripcion) VALUES ('Salsas', 'Aderezos y condimentos');
INSERT INTO categoria(nombre, descripcion) VALUES ('Enlatados', 'Conservas y productos en lata');
INSERT INTO categoria(nombre, descripcion) VALUES ('Bebés', 'Productos para bebé');
INSERT INTO proveedor(nombre, telefono, correo, direccion) VALUES ('Proveedor 01', '5550-1001', 'proveedor01@tienda.gt', 'Zona 2, Ciudad de Guatemala');
INSERT INTO proveedor(nombre, telefono, correo, direccion) VALUES ('Proveedor 02', '5550-1002', 'proveedor02@tienda.gt', 'Zona 3, Ciudad de Guatemala');
INSERT INTO proveedor(nombre, telefono, correo, direccion) VALUES ('Proveedor 03', '5550-1003', 'proveedor03@tienda.gt', 'Zona 4, Ciudad de Guatemala');
INSERT INTO proveedor(nombre, telefono, correo, direccion) VALUES ('Proveedor 04', '5550-1004', 'proveedor04@tienda.gt', 'Zona 5, Ciudad de Guatemala');
INSERT INTO proveedor(nombre, telefono, correo, direccion) VALUES ('Proveedor 05', '5550-1005', 'proveedor05@tienda.gt', 'Zona 6, Ciudad de Guatemala');
INSERT INTO proveedor(nombre, telefono, correo, direccion) VALUES ('Proveedor 06', '5550-1006', 'proveedor06@tienda.gt', 'Zona 7, Ciudad de Guatemala');
INSERT INTO proveedor(nombre, telefono, correo, direccion) VALUES ('Proveedor 07', '5550-1007', 'proveedor07@tienda.gt', 'Zona 8, Ciudad de Guatemala');
INSERT INTO proveedor(nombre, telefono, correo, direccion) VALUES ('Proveedor 08', '5550-1008', 'proveedor08@tienda.gt', 'Zona 9, Ciudad de Guatemala');
INSERT INTO proveedor(nombre, telefono, correo, direccion) VALUES ('Proveedor 09', '5550-1009', 'proveedor09@tienda.gt', 'Zona 10, Ciudad de Guatemala');
INSERT INTO proveedor(nombre, telefono, correo, direccion) VALUES ('Proveedor 10', '5550-1010', 'proveedor10@tienda.gt', 'Zona 11, Ciudad de Guatemala');
INSERT INTO proveedor(nombre, telefono, correo, direccion) VALUES ('Proveedor 11', '5550-1011', 'proveedor11@tienda.gt', 'Zona 12, Ciudad de Guatemala');
INSERT INTO proveedor(nombre, telefono, correo, direccion) VALUES ('Proveedor 12', '5550-1012', 'proveedor12@tienda.gt', 'Zona 13, Ciudad de Guatemala');
INSERT INTO proveedor(nombre, telefono, correo, direccion) VALUES ('Proveedor 13', '5550-1013', 'proveedor13@tienda.gt', 'Zona 14, Ciudad de Guatemala');
INSERT INTO proveedor(nombre, telefono, correo, direccion) VALUES ('Proveedor 14', '5550-1014', 'proveedor14@tienda.gt', 'Zona 15, Ciudad de Guatemala');
INSERT INTO proveedor(nombre, telefono, correo, direccion) VALUES ('Proveedor 15', '5550-1015', 'proveedor15@tienda.gt', 'Zona 16, Ciudad de Guatemala');
INSERT INTO proveedor(nombre, telefono, correo, direccion) VALUES ('Proveedor 16', '5550-1016', 'proveedor16@tienda.gt', 'Zona 17, Ciudad de Guatemala');
INSERT INTO proveedor(nombre, telefono, correo, direccion) VALUES ('Proveedor 17', '5550-1017', 'proveedor17@tienda.gt', 'Zona 18, Ciudad de Guatemala');
INSERT INTO proveedor(nombre, telefono, correo, direccion) VALUES ('Proveedor 18', '5550-1018', 'proveedor18@tienda.gt', 'Zona 1, Ciudad de Guatemala');
INSERT INTO proveedor(nombre, telefono, correo, direccion) VALUES ('Proveedor 19', '5550-1019', 'proveedor19@tienda.gt', 'Zona 2, Ciudad de Guatemala');
INSERT INTO proveedor(nombre, telefono, correo, direccion) VALUES ('Proveedor 20', '5550-1020', 'proveedor20@tienda.gt', 'Zona 3, Ciudad de Guatemala');
INSERT INTO proveedor(nombre, telefono, correo, direccion) VALUES ('Proveedor 21', '5550-1021', 'proveedor21@tienda.gt', 'Zona 4, Ciudad de Guatemala');
INSERT INTO proveedor(nombre, telefono, correo, direccion) VALUES ('Proveedor 22', '5550-1022', 'proveedor22@tienda.gt', 'Zona 5, Ciudad de Guatemala');
INSERT INTO proveedor(nombre, telefono, correo, direccion) VALUES ('Proveedor 23', '5550-1023', 'proveedor23@tienda.gt', 'Zona 6, Ciudad de Guatemala');
INSERT INTO proveedor(nombre, telefono, correo, direccion) VALUES ('Proveedor 24', '5550-1024', 'proveedor24@tienda.gt', 'Zona 7, Ciudad de Guatemala');
INSERT INTO proveedor(nombre, telefono, correo, direccion) VALUES ('Proveedor 25', '5550-1025', 'proveedor25@tienda.gt', 'Zona 8, Ciudad de Guatemala');
INSERT INTO cliente(nombre, nit, correo, telefono) VALUES ('Cliente 01', 'CF-10001', 'cliente01@correo.gt', '4400-2001');
INSERT INTO cliente(nombre, nit, correo, telefono) VALUES ('Cliente 02', 'CF-10002', 'cliente02@correo.gt', '4400-2002');
INSERT INTO cliente(nombre, nit, correo, telefono) VALUES ('Cliente 03', 'CF-10003', 'cliente03@correo.gt', '4400-2003');
INSERT INTO cliente(nombre, nit, correo, telefono) VALUES ('Cliente 04', 'CF-10004', 'cliente04@correo.gt', '4400-2004');
INSERT INTO cliente(nombre, nit, correo, telefono) VALUES ('Cliente 05', 'CF-10005', 'cliente05@correo.gt', '4400-2005');
INSERT INTO cliente(nombre, nit, correo, telefono) VALUES ('Cliente 06', 'CF-10006', 'cliente06@correo.gt', '4400-2006');
INSERT INTO cliente(nombre, nit, correo, telefono) VALUES ('Cliente 07', 'CF-10007', 'cliente07@correo.gt', '4400-2007');
INSERT INTO cliente(nombre, nit, correo, telefono) VALUES ('Cliente 08', 'CF-10008', 'cliente08@correo.gt', '4400-2008');
INSERT INTO cliente(nombre, nit, correo, telefono) VALUES ('Cliente 09', 'CF-10009', 'cliente09@correo.gt', '4400-2009');
INSERT INTO cliente(nombre, nit, correo, telefono) VALUES ('Cliente 10', 'CF-10010', 'cliente10@correo.gt', '4400-2010');
INSERT INTO cliente(nombre, nit, correo, telefono) VALUES ('Cliente 11', 'CF-10011', 'cliente11@correo.gt', '4400-2011');
INSERT INTO cliente(nombre, nit, correo, telefono) VALUES ('Cliente 12', 'CF-10012', 'cliente12@correo.gt', '4400-2012');
INSERT INTO cliente(nombre, nit, correo, telefono) VALUES ('Cliente 13', 'CF-10013', 'cliente13@correo.gt', '4400-2013');
INSERT INTO cliente(nombre, nit, correo, telefono) VALUES ('Cliente 14', 'CF-10014', 'cliente14@correo.gt', '4400-2014');
INSERT INTO cliente(nombre, nit, correo, telefono) VALUES ('Cliente 15', 'CF-10015', 'cliente15@correo.gt', '4400-2015');
INSERT INTO cliente(nombre, nit, correo, telefono) VALUES ('Cliente 16', 'CF-10016', 'cliente16@correo.gt', '4400-2016');
INSERT INTO cliente(nombre, nit, correo, telefono) VALUES ('Cliente 17', 'CF-10017', 'cliente17@correo.gt', '4400-2017');
INSERT INTO cliente(nombre, nit, correo, telefono) VALUES ('Cliente 18', 'CF-10018', 'cliente18@correo.gt', '4400-2018');
INSERT INTO cliente(nombre, nit, correo, telefono) VALUES ('Cliente 19', 'CF-10019', 'cliente19@correo.gt', '4400-2019');
INSERT INTO cliente(nombre, nit, correo, telefono) VALUES ('Cliente 20', 'CF-10020', 'cliente20@correo.gt', '4400-2020');
INSERT INTO cliente(nombre, nit, correo, telefono) VALUES ('Cliente 21', 'CF-10021', 'cliente21@correo.gt', '4400-2021');
INSERT INTO cliente(nombre, nit, correo, telefono) VALUES ('Cliente 22', 'CF-10022', 'cliente22@correo.gt', '4400-2022');
INSERT INTO cliente(nombre, nit, correo, telefono) VALUES ('Cliente 23', 'CF-10023', 'cliente23@correo.gt', '4400-2023');
INSERT INTO cliente(nombre, nit, correo, telefono) VALUES ('Cliente 24', 'CF-10024', 'cliente24@correo.gt', '4400-2024');
INSERT INTO cliente(nombre, nit, correo, telefono) VALUES ('Cliente 25', 'CF-10025', 'cliente25@correo.gt', '4400-2025');
INSERT INTO empleado(nombre, puesto, correo) VALUES ('Empleado 01', 'Cajero', 'empleado01@tienda.gt');
INSERT INTO empleado(nombre, puesto, correo) VALUES ('Empleado 02', 'Vendedor', 'empleado02@tienda.gt');
INSERT INTO empleado(nombre, puesto, correo) VALUES ('Empleado 03', 'Supervisor', 'empleado03@tienda.gt');
INSERT INTO empleado(nombre, puesto, correo) VALUES ('Empleado 04', 'Bodeguero', 'empleado04@tienda.gt');
INSERT INTO empleado(nombre, puesto, correo) VALUES ('Empleado 05', 'Encargado de tienda', 'empleado05@tienda.gt');
INSERT INTO empleado(nombre, puesto, correo) VALUES ('Empleado 06', 'Cajero', 'empleado06@tienda.gt');
INSERT INTO empleado(nombre, puesto, correo) VALUES ('Empleado 07', 'Vendedor', 'empleado07@tienda.gt');
INSERT INTO empleado(nombre, puesto, correo) VALUES ('Empleado 08', 'Supervisor', 'empleado08@tienda.gt');
INSERT INTO empleado(nombre, puesto, correo) VALUES ('Empleado 09', 'Bodeguero', 'empleado09@tienda.gt');
INSERT INTO empleado(nombre, puesto, correo) VALUES ('Empleado 10', 'Encargado de tienda', 'empleado10@tienda.gt');
INSERT INTO empleado(nombre, puesto, correo) VALUES ('Empleado 11', 'Cajero', 'empleado11@tienda.gt');
INSERT INTO empleado(nombre, puesto, correo) VALUES ('Empleado 12', 'Vendedor', 'empleado12@tienda.gt');
INSERT INTO empleado(nombre, puesto, correo) VALUES ('Empleado 13', 'Supervisor', 'empleado13@tienda.gt');
INSERT INTO empleado(nombre, puesto, correo) VALUES ('Empleado 14', 'Bodeguero', 'empleado14@tienda.gt');
INSERT INTO empleado(nombre, puesto, correo) VALUES ('Empleado 15', 'Encargado de tienda', 'empleado15@tienda.gt');
INSERT INTO empleado(nombre, puesto, correo) VALUES ('Empleado 16', 'Cajero', 'empleado16@tienda.gt');
INSERT INTO empleado(nombre, puesto, correo) VALUES ('Empleado 17', 'Vendedor', 'empleado17@tienda.gt');
INSERT INTO empleado(nombre, puesto, correo) VALUES ('Empleado 18', 'Supervisor', 'empleado18@tienda.gt');
INSERT INTO empleado(nombre, puesto, correo) VALUES ('Empleado 19', 'Bodeguero', 'empleado19@tienda.gt');
INSERT INTO empleado(nombre, puesto, correo) VALUES ('Empleado 20', 'Encargado de tienda', 'empleado20@tienda.gt');
INSERT INTO empleado(nombre, puesto, correo) VALUES ('Empleado 21', 'Cajero', 'empleado21@tienda.gt');
INSERT INTO empleado(nombre, puesto, correo) VALUES ('Empleado 22', 'Vendedor', 'empleado22@tienda.gt');
INSERT INTO empleado(nombre, puesto, correo) VALUES ('Empleado 23', 'Supervisor', 'empleado23@tienda.gt');
INSERT INTO empleado(nombre, puesto, correo) VALUES ('Empleado 24', 'Bodeguero', 'empleado24@tienda.gt');
INSERT INTO empleado(nombre, puesto, correo) VALUES ('Empleado 25', 'Encargado de tienda', 'empleado25@tienda.gt');
INSERT INTO producto(nombre, precio, stock, id_categoria, id_proveedor) VALUES ('Agua pura 1L', 7.35, 23, 1, 1);
INSERT INTO producto(nombre, precio, stock, id_categoria, id_proveedor) VALUES ('Galletas de avena', 9.7, 26, 2, 2);
INSERT INTO producto(nombre, precio, stock, id_categoria, id_proveedor) VALUES ('Leche entera', 12.05, 29, 3, 3);
INSERT INTO producto(nombre, precio, stock, id_categoria, id_proveedor) VALUES ('Pan integral', 14.4, 32, 4, 4);
INSERT INTO producto(nombre, precio, stock, id_categoria, id_proveedor) VALUES ('Cloro 1L', 16.75, 35, 5, 5);
INSERT INTO producto(nombre, precio, stock, id_categoria, id_proveedor) VALUES ('Shampoo familiar', 19.1, 38, 6, 6);
INSERT INTO producto(nombre, precio, stock, id_categoria, id_proveedor) VALUES ('Arroz blanco', 21.45, 41, 7, 7);
INSERT INTO producto(nombre, precio, stock, id_categoria, id_proveedor) VALUES ('Pechuga empacada', 23.8, 44, 8, 8);
INSERT INTO producto(nombre, precio, stock, id_categoria, id_proveedor) VALUES ('Pizza congelada', 26.15, 47, 9, 9);
INSERT INTO producto(nombre, precio, stock, id_categoria, id_proveedor) VALUES ('Manzana roja', 28.5, 50, 10, 10);
INSERT INTO producto(nombre, precio, stock, id_categoria, id_proveedor) VALUES ('Lechuga fresca', 30.85, 53, 11, 11);
INSERT INTO producto(nombre, precio, stock, id_categoria, id_proveedor) VALUES ('Alimento para perro', 33.2, 56, 12, 12);
INSERT INTO producto(nombre, precio, stock, id_categoria, id_proveedor) VALUES ('Cuaderno universitario', 35.55, 59, 13, 13);
INSERT INTO producto(nombre, precio, stock, id_categoria, id_proveedor) VALUES ('Cable USB-C', 37.9, 62, 14, 14);
INSERT INTO producto(nombre, precio, stock, id_categoria, id_proveedor) VALUES ('Alcohol gel', 40.25, 65, 15, 15);
INSERT INTO producto(nombre, precio, stock, id_categoria, id_proveedor) VALUES ('Sartén mediano', 42.6, 68, 16, 16);
INSERT INTO producto(nombre, precio, stock, id_categoria, id_proveedor) VALUES ('Calcetines básicos', 44.95, 71, 17, 17);
INSERT INTO producto(nombre, precio, stock, id_categoria, id_proveedor) VALUES ('Martillo pequeño', 47.3, 74, 18, 18);
INSERT INTO producto(nombre, precio, stock, id_categoria, id_proveedor) VALUES ('Tierra abonada', 49.65, 77, 19, 19);
INSERT INTO producto(nombre, precio, stock, id_categoria, id_proveedor) VALUES ('Chocolate con leche', 52.0, 80, 20, 20);
INSERT INTO producto(nombre, precio, stock, id_categoria, id_proveedor) VALUES ('Café molido', 54.35, 83, 21, 21);
INSERT INTO producto(nombre, precio, stock, id_categoria, id_proveedor) VALUES ('Cereal de maíz', 56.7, 86, 22, 22);
INSERT INTO producto(nombre, precio, stock, id_categoria, id_proveedor) VALUES ('Salsa de tomate', 59.05, 89, 23, 23);
INSERT INTO producto(nombre, precio, stock, id_categoria, id_proveedor) VALUES ('Atún en lata', 61.4, 92, 24, 24);
INSERT INTO producto(nombre, precio, stock, id_categoria, id_proveedor) VALUES ('Pañales talla M', 63.75, 95, 25, 25);
INSERT INTO venta(fecha, id_cliente, id_empleado, total) VALUES ('2026-04-02 11:00:00', 2, 3, 43.8);
INSERT INTO venta(fecha, id_cliente, id_empleado, total) VALUES ('2026-04-03 12:00:00', 3, 5, 41.15);
INSERT INTO venta(fecha, id_cliente, id_empleado, total) VALUES ('2026-04-04 13:00:00', 4, 7, 77.0);
INSERT INTO venta(fecha, id_cliente, id_empleado, total) VALUES ('2026-04-05 14:00:00', 5, 9, 64.65);
INSERT INTO venta(fecha, id_cliente, id_empleado, total) VALUES ('2026-04-06 15:00:00', 6, 11, 52.6);
INSERT INTO venta(fecha, id_cliente, id_empleado, total) VALUES ('2026-04-07 16:00:00', 7, 13, 100.2);
INSERT INTO venta(fecha, id_cliente, id_empleado, total) VALUES ('2026-04-08 17:00:00', 8, 15, 157.2);
INSERT INTO venta(fecha, id_cliente, id_empleado, total) VALUES ('2026-04-09 10:00:00', 9, 17, 49.95);
INSERT INTO venta(fecha, id_cliente, id_empleado, total) VALUES ('2026-04-10 11:00:00', 10, 19, 109.3);
INSERT INTO venta(fecha, id_cliente, id_empleado, total) VALUES ('2026-04-11 12:00:00', 11, 21, 178.05);
INSERT INTO venta(fecha, id_cliente, id_empleado, total) VALUES ('2026-04-12 13:00:00', 12, 23, 156.6);
INSERT INTO venta(fecha, id_cliente, id_empleado, total) VALUES ('2026-04-13 14:00:00', 13, 25, 104.3);
INSERT INTO venta(fecha, id_cliente, id_empleado, total) VALUES ('2026-04-14 15:00:00', 14, 2, 184.8);
INSERT INTO venta(fecha, id_cliente, id_empleado, total) VALUES ('2026-04-15 16:00:00', 15, 4, 153.95);
INSERT INTO venta(fecha, id_cliente, id_empleado, total) VALUES ('2026-04-16 17:00:00', 16, 6, 246.2);
INSERT INTO venta(fecha, id_cliente, id_empleado, total) VALUES ('2026-04-17 10:00:00', 17, 8, 177.45);
INSERT INTO venta(fecha, id_cliente, id_empleado, total) VALUES ('2026-04-18 11:00:00', 18, 10, 137.2);
INSERT INTO venta(fecha, id_cliente, id_empleado, total) VALUES ('2026-04-19 12:00:00', 19, 12, 241.2);
INSERT INTO venta(fecha, id_cliente, id_empleado, total) VALUES ('2026-04-20 13:00:00', 20, 14, 354.6);
INSERT INTO venta(fecha, id_cliente, id_empleado, total) VALUES ('2026-04-01 14:00:00', 21, 16, 106.35);
INSERT INTO venta(fecha, id_cliente, id_empleado, total) VALUES ('2026-04-02 15:00:00', 22, 18, 222.1);
INSERT INTO venta(fecha, id_cliente, id_empleado, total) VALUES ('2026-04-03 16:00:00', 23, 20, 347.25);
INSERT INTO venta(fecha, id_cliente, id_empleado, total) VALUES ('2026-04-04 17:00:00', 24, 22, 297.6);
INSERT INTO venta(fecha, id_cliente, id_empleado, total) VALUES ('2026-04-05 10:00:00', 25, 24, 188.9);
INSERT INTO venta(fecha, id_cliente, id_empleado, total) VALUES ('2026-04-06 11:00:00', 1, 1, 149.55);
INSERT INTO detalle_venta(id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (1, 1, 2, 7.35, 14.7);
INSERT INTO detalle_venta(id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (2, 2, 3, 9.7, 29.1);
INSERT INTO detalle_venta(id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (3, 3, 4, 12.05, 48.2);
INSERT INTO detalle_venta(id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (4, 4, 1, 14.4, 14.4);
INSERT INTO detalle_venta(id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (5, 5, 2, 16.75, 33.5);
INSERT INTO detalle_venta(id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (6, 6, 3, 19.1, 57.3);
INSERT INTO detalle_venta(id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (7, 7, 4, 21.45, 85.8);
INSERT INTO detalle_venta(id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (8, 8, 1, 23.8, 23.8);
INSERT INTO detalle_venta(id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (9, 9, 2, 26.15, 52.3);
INSERT INTO detalle_venta(id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (10, 10, 3, 28.5, 85.5);
INSERT INTO detalle_venta(id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (11, 11, 4, 30.85, 123.4);
INSERT INTO detalle_venta(id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (12, 12, 1, 33.2, 33.2);
INSERT INTO detalle_venta(id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (13, 13, 2, 35.55, 71.1);
INSERT INTO detalle_venta(id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (14, 14, 3, 37.9, 113.7);
INSERT INTO detalle_venta(id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (15, 15, 4, 40.25, 161.0);
INSERT INTO detalle_venta(id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (16, 16, 1, 42.6, 42.6);
INSERT INTO detalle_venta(id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (17, 17, 2, 44.95, 89.9);
INSERT INTO detalle_venta(id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (18, 18, 3, 47.3, 141.9);
INSERT INTO detalle_venta(id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (19, 19, 4, 49.65, 198.6);
INSERT INTO detalle_venta(id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (20, 20, 1, 52.0, 52.0);
INSERT INTO detalle_venta(id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (21, 21, 2, 54.35, 108.7);
INSERT INTO detalle_venta(id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (22, 22, 3, 56.7, 170.1);
INSERT INTO detalle_venta(id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (23, 23, 4, 59.05, 236.2);
INSERT INTO detalle_venta(id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (24, 24, 1, 61.4, 61.4);
INSERT INTO detalle_venta(id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES (25, 25, 2, 63.75, 127.5);
